CREATE TABLE IF NOT EXISTS Chief(
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Employee(
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	department VARCHAR(60) NOT NULL,
	Chief_id INTEGER NOT NULL REFERENCES Chief(id)